#!/bin/sh
COLOR_NC='\e[0m' # No Color
COLOR_WHITE='\e[1;37m'
COLOR_BLACK='\e[0;30m'
COLOR_BLUE='\e[0;34m'
COLOR_LIGHT_BLUE='\e[1;34m'
COLOR_GREEN='\e[0;32m'
COLOR_LIGHT_GREEN='\e[1;32m'
COLOR_CYAN='\e[0;36m'
COLOR_LIGHT_CYAN='\e[1;36m'
COLOR_RED='\e[0;31m'
COLOR_LIGHT_RED='\e[1;31m'
COLOR_PURPLE='\e[0;35m'
COLOR_LIGHT_PURPLE='\e[1;35m'
COLOR_BROWN='\e[0;33m'
COLOR_YELLOW='\e[1;33m'
COLOR_GRAY='\e[0;30m'
COLOR_LIGHT_GRAY='\e[0;37m'

if [ "$1" = "" ]
then
  echo "${COLOR_LIGHT_BLUE}Usage: ${COLOR_LIGHT_GREEN}./wwwtf google.com"
  exit
fi

echo "${COLOR_YELLOW}Looking up IP..."
IP=$(ping -c1 $1 | sed -nE 's/^PING[^(]+\(([^)]+)\).*/\1/p')
echo "${COLOR_BLUE}Hosted on:"
echo "${COLOR_LIGHT_GREEN}${IP}"


echo "${COLOR_YELLOW}Looking up DNS..."
for ip in $IP
do
	echo "${COLOR_BLUE}Hosts on ${ip}:${COLOR_LIGHT_GREEN}"
	host $ip
done


echo "${COLOR_YELLOW}Scanning ports..."
for ip in $IP
do
	echo "${COLOR_BLUE}Open ports on ${ip}:${COLOR_LIGHT_GREEN}"
	nmap $ip | grep "open"
done


echo "${COLOR_YELLOW}Just a bit curl..."
for ip in $IP
do
	echo "${COLOR_BLUE}Response from ${ip}:${COLOR_LIGHT_GREEN}"
	curl -I $ip
done

